C--**--CH165--524--C:D--20:5:1999
C--**--CH164--524--U:D--20:5:1999
      SUBROUTINE MPUPK (SOURCE, DEST, LDEST, LFIELD)                    
      integer I, IST, ISTC, K, LD, LDEST, LFIELD, NK
C
C              *************************    (SEE SECTION 5 OF
C              *** MACHINE DEPENDENT ***     USERS GUIDE FOR
C              *************************     CONVERSION HINTS)
C
C MACHINE-DEPENDENT STATEMENTS ARE SURROUNDED BY C *** LINES
C ***
C THIS IS UNIVAC 1100, FORTRAN V VERSION.
C ***
C THIS SUBROUTINE UNPACKS A PACKED HOLLERITH STRING (SOURCE)
C PLACING ONE CHARACTER PER WORD IN THE ARRAY DEST (AS IF READ IN
C A1 FORMAT). IT CONTINUES UNPACKING UNTIL IT FINDS A SENTINEL ($)
C OR UNTIL IT FINDS A COMPILER GENERATED SENTINEL (IF SO
C IMPLEMENTED) OR UNTIL IT HAS FILLED LDEST WORDS OF THE
C ARRAY DEST.  THE LENGTH OF THE UNPACKED STRING IS RETURNED
C IN LFIELD.   THUS 0 .LE. LFIELD .LE. LDEST.
      INTEGER SOURCE(1), DEST(1), BLANKS, TEMP
      DATA BLANKS /1H /, IST /1H$/
C NK IS THE NUMBER OF CHARACTERS PER WORD
C AND ISTC IS THE COMPILER-GENERATED SENTINEL (IF ANY)
C ***
      DATA NK /6/, ISTC /0/
C ***
      TEMP = BLANKS
      LD = LDEST
      LFIELD = 0
      IF (LD.LE.0) RETURN
      DO 10 K = 1, LD
      I = LFIELD/NK + 1
C GET NEXT WORD (CONTAINING NK CHARACTERS) AND
C CHECK FOR COMPILER-GENERATED END-OF-STRING SENTINEL
      IF (SOURCE(I) .EQ. ISTC) RETURN
C MOVE (MOD(LFIELD,NK)+1)-TH CHARACTER OF SOURCE(I) TO
C FIRST (I.E. LEFTMOST) CHARACTER POSITION OF TEMP
C ***
C     FLD (0, 6, TEMP) = FLD (6*MOD(LFIELD,6), 6, SOURCE(I))
C ***
C CHECK FOR END-OF-STRING SENTINEL
      IF (TEMP .EQ. IST)  RETURN
      LFIELD = K
      DEST(K) = TEMP
10    CONTINUE
      RETURN
      END
